FROM gradle:jdk11 as builder
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build -x test

FROM openjdk:11
EXPOSE 8089
COPY --from=builder /home/gradle/src/build/libs/*.jar /products.jar
ENV JAVA_OPTS=""
CMD java ${JAVA_OPTS} -jar /products.jar
