version: '2.1'
services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=products
    ports:
      - "5433:5432"
  products:
    build:
      context: .
      dockerfile: Dockerfile-local
    image: "products"
    depends_on:
      - "postgres"
    links:
      - "postgres:postgres"
    restart: always
    ports:
      - "8089:8089"